MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0001
  GAMMA: 0.1
  MAX_ITER: 100000
  STEPS: [0, 80000, 90000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
# Coarsest level of the FPN pyramid
  ROI_MAX_LEVEL: 5
# Finest level of the FPN pyramid
  ROI_MIN_LEVEL: 3
# Coarsest level of the FPN pyramid
  RPN_MAX_LEVEL: 6
# Finest level of the FPN pyramid
  RPN_MIN_LEVEL: 3

FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
#  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  WEIGHTS: /home/long/github/detectron/models/detectron/e2e_faster_rcnn_R-50-FPN_2x.pkl
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALES: (500,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 100  # Per FPN level
  RPN_POST_NMS_TOP_N: 20
OUTPUT_DIR: .
