MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_MobileNet_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 100000
  STEPS: [0, 80000, 90000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: /home/long/github/detectron/models/detectron/ImageNetPretrained/mobilenet.pkl
#  WEIGHTS: /home/long/github/detectron/models/detectron/e2e_faster_rcnn_R-50-FPN_2x.pkl
#  WEIGHTS: /home/long/github/detectron/models/detectron/ImageNetPretrained/R-50.pkl
  #https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('fisher_train_221','fisher_val_221')
  SCALES: (300,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('fisher_valtt_221',)
  FORCE_JSON_DATASET_EVAL: True
  SCALES: (300,)
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 200
OUTPUT_DIR: .
